name = "The Dock"
author = "pengeg"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58c38cfc7ad597fe869181b4f9a5896ddbb3e433fb874528b203cd7552d84a15"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
