name = "The Dock"
author = "pengeg"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54131a8ed977578e46aa26bbcdcf3a724f5fed4124ae449bc6d6fa39e34d8b64"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
