name = "The Dock"
author = "pengeg"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be5c635bd41e790072756e291c3fec0a90aa55ba7534bf1aafb75e57cddb2773"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
