name = "The Dock"
author = "pengeg"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0676203c68cacf6532c62c213644f744c281509c01de2b3ec552c1ae0af4900e"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
